### ISSUE TITLE
Кривое расположение .b-replies

### ISSUE THREAD

**Issue by Astatoru** [Dedonych/Shikimori-Dark-Theme#1]
- В данный момент у **.b-replies** используется **position: absolute**, из-за этого ответы под некоторыми комментариями имеют неправильное расположение:
`.b-replies {
  position: absolute; }`
![image](https://github.com/user-attachments/assets/fb041534-edf6-4f05-8d7e-2a4e1d208425)

- **position: relative** решает эту проблему:
`.b-replies {
  position: relative; }`
![image](https://github.com/user-attachments/assets/6ffee38e-d2be-43e1-b363-00edd615cf81)

**Comment by Dedonych** [comment]
Пофиксил
